services:
  fastapi:
    build:
      context: .
      dockerfile: ./app/api/Dockerfile
    ports:
      - 8000:8000
    environment:
      - API_KEY
      - DATA_FILE_PATH
      - HOST
      - PORT

  streamlit:
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
